// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEeNiMrFROMuzdG1vA8drYj8Uc_At3gQ',
    appId: '1:536889383652:web:85f3f251ae2e9552182af1',
    messagingSenderId: '536889383652',
    projectId: 'fridge-7e2e1',
    authDomain: 'fridge-7e2e1.firebaseapp.com',
    storageBucket: 'fridge-7e2e1.firebasestorage.app',
    measurementId: 'G-6ZNFZXLVS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADbdDtXgiBGc_yT35WbwlEFXb1KFweec',
    appId: '1:536889383652:android:3d53c0d015c4095f182af1',
    messagingSenderId: '536889383652',
    projectId: 'fridge-7e2e1',
    storageBucket: 'fridge-7e2e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBklgknDEJsZ2qiWWyHeVtGdg5HqSss6CY',
    appId: '1:536889383652:ios:c534092af3a04922182af1',
    messagingSenderId: '536889383652',
    projectId: 'fridge-7e2e1',
    storageBucket: 'fridge-7e2e1.firebasestorage.app',
    androidClientId: '536889383652-a41bseh0klsf3agl0fgac36hvu3m2e54.apps.googleusercontent.com',
    iosClientId: '536889383652-a17q92okqbdcgvmr2l82qnfgs7hsklhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBklgknDEJsZ2qiWWyHeVtGdg5HqSss6CY',
    appId: '1:536889383652:ios:c534092af3a04922182af1',
    messagingSenderId: '536889383652',
    projectId: 'fridge-7e2e1',
    storageBucket: 'fridge-7e2e1.firebasestorage.app',
    androidClientId: '536889383652-a41bseh0klsf3agl0fgac36hvu3m2e54.apps.googleusercontent.com',
    iosClientId: '536889383652-a17q92okqbdcgvmr2l82qnfgs7hsklhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMEeNiMrFROMuzdG1vA8drYj8Uc_At3gQ',
    appId: '1:536889383652:web:5baa1287ce381693182af1',
    messagingSenderId: '536889383652',
    projectId: 'fridge-7e2e1',
    authDomain: 'fridge-7e2e1.firebaseapp.com',
    storageBucket: 'fridge-7e2e1.firebasestorage.app',
    measurementId: 'G-MZ6RPJQZCC',
  );
}
